import { prisma } from "@/lib/prisma.js";
import Step from "@/workflow-runner/steps/step.js";

export default class AgentStep extends Step {
    private agentId: string;

    constructor(agentId: string) {
        super();
        this.agentId = agentId;
    }

    async execute(input?: string): Promise<string> {
        const agent = await prisma.agent.findUnique({
            where: { id: this.agentId },
        });

        if (!agent)
            throw new Error(`Agent with id ${this.agentId} not found`);

        if (agent.model !== "gemini_2_5_flash") {
            throw new Error(`Model ${agent.model} is not supported. Only gemini_2_5_flash is currently supported.`);
        }

        const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
        if (!GEMINI_API_KEY) {
            throw new Error('GEMINI_API_KEY environment variable is not set');
        }

        const url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

        const requestBody = {
            system_instruction: {
                parts: [
                    {
                        text: agent.system_prompt
                    }
                ]
            },
            contents: [
                {
                    parts: [
                        {
                            text: input
                        }
                    ]
                }
            ],
            generationConfig: agent.temperature !== null ? {
                temperature: agent.temperature
            } : undefined
        };

        console.log('[AgentStep] Gemini API Request:', {
            url,
            agent: { id: agent.id, name: agent.name, model: agent.model },
            system_prompt: agent.system_prompt,
            input,
            temperature: agent.temperature,
        });

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'x-goog-api-key': GEMINI_API_KEY,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(requestBody),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            console.error('[AgentStep] Gemini API Error:', {
                status: response.status,
                statusText: response.statusText,
                errorData,
            });
            throw new Error(
                `Gemini API request failed: ${response.status} ${response.statusText}. ${JSON.stringify(errorData)}`
            );
        }

        const data = await response.json() as {
            candidates?: {
                content?: {
                    parts?: {
                        text?: string;
                    }[];
                };
            }[];
        };

        if (!data.candidates || data.candidates.length === 0) {
            console.error('[AgentStep] No candidates in response:', data);
            throw new Error('No content generated by Gemini API');
        }

        const generatedText = data.candidates[0]?.content?.parts?.[0]?.text || '';
        
        console.log('[AgentStep] Gemini API Response:', {
            generatedTextLength: generatedText.length,
            preview: generatedText.substring(0, 100) + (generatedText.length > 100 ? '...' : ''),
        });

        return generatedText;
    }
}
