/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowBuilderIndexRouteImport } from './routes/workflow-builder/index'
import { Route as DashboardWorkflowsRouteImport } from './routes/dashboard/workflows'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowBuilderIndexRoute = WorkflowBuilderIndexRouteImport.update({
  id: '/workflow-builder/',
  path: '/workflow-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/workflow-builder': typeof WorkflowBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/workflow-builder': typeof WorkflowBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/workflow-builder/': typeof WorkflowBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/workflows'
    | '/workflow-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/workflows'
    | '/workflow-builder'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/workflows'
    | '/workflow-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  WorkflowBuilderIndexRoute: typeof WorkflowBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-builder/': {
      id: '/workflow-builder/'
      path: '/workflow-builder'
      fullPath: '/workflow-builder'
      preLoaderRoute: typeof WorkflowBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows': {
      id: '/dashboard/workflows'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  WorkflowBuilderIndexRoute: WorkflowBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
